version: "3"
services:
  deno:
    image: maxmcd/deno:slim-v0.7.0
    working_dir: "/app"
    command: deno run --allow-net ./app.ts
    environment:
        DENO_DIR: "/app/.deno"
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
